#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v12
# autospec commit: 381dfd8
#
Name     : R-crayon
Version  : 1.5.3
Release  : 99
URL      : https://cran.r-project.org/src/contrib/crayon_1.5.3.tar.gz
Source0  : https://cran.r-project.org/src/contrib/crayon_1.5.3.tar.gz
Summary  : Colored Terminal Output
Group    : Development/Tools
License  : MIT
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
package for new projects.  Colored terminal output on terminals that
    support 'ANSI' color and highlight codes. It also works in 'Emacs'
    'ESS'. 'ANSI' color support is automatically detected. Colors and
    highlighting can be combined and nested. New styles can also be
    created easily.  This package was inspired by the 'chalk' 'JavaScript'
    project.

%prep
%setup -q -n crayon
pushd ..
cp -a crayon buildavx2
popd
pushd ..
cp -a crayon buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1718987363

%install
export SOURCE_DATE_EPOCH=1718987363
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/crayon/DESCRIPTION
/usr/lib64/R/library/crayon/INDEX
/usr/lib64/R/library/crayon/LICENSE
/usr/lib64/R/library/crayon/Meta/Rd.rds
/usr/lib64/R/library/crayon/Meta/features.rds
/usr/lib64/R/library/crayon/Meta/hsearch.rds
/usr/lib64/R/library/crayon/Meta/links.rds
/usr/lib64/R/library/crayon/Meta/nsInfo.rds
/usr/lib64/R/library/crayon/Meta/package.rds
/usr/lib64/R/library/crayon/NAMESPACE
/usr/lib64/R/library/crayon/NEWS.md
/usr/lib64/R/library/crayon/R/crayon
/usr/lib64/R/library/crayon/R/crayon.rdb
/usr/lib64/R/library/crayon/R/crayon.rdx
/usr/lib64/R/library/crayon/help/AnIndex
/usr/lib64/R/library/crayon/help/aliases.rds
/usr/lib64/R/library/crayon/help/crayon.rdb
/usr/lib64/R/library/crayon/help/crayon.rdx
/usr/lib64/R/library/crayon/help/paths.rds
/usr/lib64/R/library/crayon/html/00Index.html
/usr/lib64/R/library/crayon/html/R.css
/usr/lib64/R/library/crayon/tests/testthat.R
/usr/lib64/R/library/crayon/tests/testthat/helper.R
/usr/lib64/R/library/crayon/tests/testthat/test-ansi256.R
/usr/lib64/R/library/crayon/tests/testthat/test-color.R
/usr/lib64/R/library/crayon/tests/testthat/test-combine.R
/usr/lib64/R/library/crayon/tests/testthat/test-has-style.R
/usr/lib64/R/library/crayon/tests/testthat/test-hyperlink.R
/usr/lib64/R/library/crayon/tests/testthat/test-make-style.R
/usr/lib64/R/library/crayon/tests/testthat/test-operations.R
/usr/lib64/R/library/crayon/tests/testthat/test-style-var.R
/usr/lib64/R/library/crayon/tests/testthat/test-styles.R
/usr/lib64/R/library/crayon/tests/testthat/test-utils.R
/usr/lib64/R/library/crayon/tests/testthat/test-vectors.R
