#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-crayon
Version  : 1.3.2
Release  : 27
URL      : http://cran.r-project.org/src/contrib/crayon_1.3.2.tar.gz
Source0  : http://cran.r-project.org/src/contrib/crayon_1.3.2.tar.gz
Summary  : Colored Terminal Output
Group    : Development/Tools
License  : MIT
BuildRequires : clr-R-helpers

%description
<h1 align="center">
<br>
<br>
<img width="400" src="./inst/logo.png" alt="crayon">
<br>
<br>
<br>
</h1>

%prep
%setup -q -c -n crayon

%build
export LANG=C
export SOURCE_DATE_EPOCH=1484532500

%install
rm -rf %{buildroot}
export SOURCE_DATE_EPOCH=1484532500
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library crayon
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library crayon


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/crayon/ANSI-256-OSX.png
/usr/lib64/R/library/crayon/ANSI-8-OSX.png
/usr/lib64/R/library/crayon/DESCRIPTION
/usr/lib64/R/library/crayon/INDEX
/usr/lib64/R/library/crayon/LICENSE
/usr/lib64/R/library/crayon/Meta/Rd.rds
/usr/lib64/R/library/crayon/Meta/hsearch.rds
/usr/lib64/R/library/crayon/Meta/links.rds
/usr/lib64/R/library/crayon/Meta/nsInfo.rds
/usr/lib64/R/library/crayon/Meta/package.rds
/usr/lib64/R/library/crayon/NAMESPACE
/usr/lib64/R/library/crayon/NEWS.md
/usr/lib64/R/library/crayon/R/crayon
/usr/lib64/R/library/crayon/R/crayon.rdb
/usr/lib64/R/library/crayon/R/crayon.rdx
/usr/lib64/R/library/crayon/README.markdown
/usr/lib64/R/library/crayon/help/AnIndex
/usr/lib64/R/library/crayon/help/aliases.rds
/usr/lib64/R/library/crayon/help/crayon.rdb
/usr/lib64/R/library/crayon/help/crayon.rdx
/usr/lib64/R/library/crayon/help/paths.rds
/usr/lib64/R/library/crayon/html/00Index.html
/usr/lib64/R/library/crayon/html/R.css
/usr/lib64/R/library/crayon/logo.png
/usr/lib64/R/library/crayon/logo.svg.gz
